#!/bin/bash
# Common UV commands for this project

echo "=== UV Commands for Topic Modeling Project ==="
echo ""
echo "✓ Virtual environment is automatically managed by UV"
echo "✓ Dependencies are installed and working"
echo ""
echo "Install dependencies:"
echo "  uv sync"
echo ""
echo "Install with dev dependencies:"
echo "  uv sync --extra dev"
echo ""
echo "Run the main application:"
echo "  uv run main.py"
echo ""
echo "Add a new dependency:"
echo "  uv add package-name"
echo ""
echo "Add a dev dependency:"
echo "  uv add --dev package-name"
echo ""
echo "Run tests:"
echo "  uv run pytest"
echo ""
echo "Lint and format code with Ruff:"
echo "  uv run ruff check .          # Check for issues"
echo "  uv run ruff format .         # Format code"
echo "  uv run ruff check --fix .    # Auto-fix issues"
echo ""
echo "Show project info:"
echo "  uv show"
echo ""
echo "Activate shell:"
echo "  uv shell"
echo ""
echo "Test the WCSVNtm package:"
echo "  uv run python -c \"from WCSVNtm import run_wcsvntm; print('Working!')\""
